In [5]:
import pandas as pd
import numpy as np
import tensorflow as tf
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import scale
# import custon functions
# from utils import process_data

In [6]:
data = tf.keras.datasets.mnist.load_data(
    path='mnist.npz'
)

In [7]:
def process_data(data):
    print("pre-processing data")
    X = np.array(data[0][0])
    y = np.array(data[0][1])
    X_flat = []
    for i in range(len(X)):
        X_flat.append(X[i].flatten())
    X = np.array(X_flat)
    X_scaled = scale(X)
    # X_flat.shape
    return train_test_split(X_scaled,y, test_size = 0.3, train_size = 0.2 ,random_state = 10)

In [8]:
X_train, X_test, y_train, y_test = process_data(data)

pre-processing data


In [9]:
from sklearn.svm import SVC
model_linear = SVC(kernel='linear')
model_linear.fit(X_train, y_train)

# predict
y_pred = model_linear.predict(X_test)

In [10]:
# confusion matrix and accuracy

from sklearn import metrics
from sklearn.metrics import confusion_matrix
# accuracy
print("accuracy:", metrics.accuracy_score(y_true=y_test, y_pred=y_pred), "\n")

# cm
print(metrics.confusion_matrix(y_true=y_test, y_pred=y_pred))

accuracy: 0.9103333333333333 

[[1719    0   10    5    3   16   12    1    6    0]
 [   1 1951   11    5    5    4    0    3   11    1]
 [  11   26 1676   30   23    5   23   19   17    1]
 [  10    4   47 1627    4   66    5   19   42   10]
 [   4    8   21    1 1658    5   14    6    5   50]
 [  21    9   19   87   12 1423   30    1   39   11]
 [  20    7   23    1   14   20 1666    2    4    0]
 [   7   13   19   16   31    4    2 1774    5   93]
 [  25   44   49   54   12   58   18   11 1436   17]
 [   4   11   19   23   90    9    1   69   20 1456]]
